[package]
description = "State machine for VT100-like terminal data streams"
edition = "2021"
license = "MIT"
name = "vtmachine"
repository = "https://github.com/apparentlymart/rust-vtmachine"
version = "0.2.0"

[dependencies]
u8char = "0.3.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
